### ISSUE TITLE
CemUI does not want to read SMM in the correct sturcture format

### ISSUE THREAD

**Issue by timmehz** [RedDuckss/CemUI#101]
so, I have tried out this CemUI out just today so I am new about this whole application but I seem on getting errors with JavaScript that it can't locate any games on the folder I told it to look in, here is some pictures to have a better understanding of what I mean.
![screenshot_1](https://user-images.githubusercontent.com/34901910/39792091-35a5279c-52fc-11e8-8cec-cec8e6e2c504.png)
![screenshot_2](https://user-images.githubusercontent.com/34901910/39792092-35c1c97e-52fc-11e8-9f5f-aec8af31ce4e.png)

**Comment by RedDuckss** [comment]
After looking at the error a bit closer, I know the exact problem. Sadly I am unable to fix it right now. The issue is happening because of a bug on the API server, and is related to #98, #100, #92, and #91 

I went over this issue here https://github.com/RedDuckss/CemUI/issues/100#issuecomment-380495144

**Comment by RedDuckss** [comment]
No. As I said in the comment I linked.

**Comment by timmehz** [comment]
ok

**Comment by timmehz** [comment]
well if you want I can help you, I know abit of HTML, CSS, and JavaScript (drawing and animation)

**Comment by RedDuckss** [comment]
Issue's have been fixed, it was a server side issue that I didn't have time to resolve until now. The proper API version is back online (I still have no idea why it started using v1 again). All should be well.
