### ISSUE TITLE
The Hud is Garbage

### ISSUE THREAD

**Issue by Banjero** [RedDuckss/CemUI#102]
When i installed the software first i got a java error when i selected the gamefolder. 
Cemu and Gamefolder was both in documents. So i changed the cemu folder and now i get the error when i start cemui.

So 2 things which garbage. First - ask me for the installation folder and second - integrate the options in the task.

I tried everything - tried ccleaner but i get the error and than nothing happens.

**Comment by RedDuckss** [comment]
Judging by the title I can already see this issue report will just be angry and non-helpful.

```
When i installed the software first i got a java error when i selected the gamefolder.
```
1) There is no Java here.
2) Did you even read the issue reporting template, or just ignore it? Because it clearly states that if an error messages is shown to provide a screenshot of it

```
Cemu and Gamefolder was both in documents. So i changed the cemu folder and now i get the error when i start cemui.
```
See above

```
ask me for the installation folder
```
Back when this project was maintained (which it isn't right now, and I've said so in other issue reports) the package we used for building did not allow for this. It would install to the folder described in the Electron spec, as it should. Whether or not this is supported now is a question I have not looked into, as again this project is not maintained right now

```
integrate the options in the task
```
This sentence makes no sense and seemingly has no relevance to the issue.

I'm going to close this issue report for 3 reasons:
1) It is unhelpful and provides no useful information
2) The issue reporting format was completely ignored
3) Of the issues that you actually described, all of them have already been reported, making this report useless
