### ISSUE TITLE
"A JavaScript error occurred in the main process"

### ISSUE THREAD

**Issue by Nayrboh** [RedDuckss/CemUI#23]
http://imgur.com/a/pQpOe

https://youtu.be/bfSp8nAowoc

so when I try to scan for games it loads for a second and then the error, shown above, appears once for every game, after pressing "OK" it continues to load and opens without any games loaded.

I have tried every way to download it / compile it and still no luck...

**Comment by RedDuckss** [comment]
Woops!! Looks like I forgot to update the `README` to explain the current situation. Yes, I have begun working on CemUI again however the current release as well as the source code in the master branch is outdated. The reason this issue you have happens is because I only recently put the API back online, and I have not linked the `cemui.com` domain to it yet (it's still in dev-mode), so CemUI is checking for an API that isn't online on a domain that doesn't exist. The master branch will not be getting any updates for a while, since I am rewrite the entire program from scratch. Check the `2.0` branch for updates, though the UI is _NOT_ functional atm.

I am going to leave this report open for now, until I link the cemui.com domain back to the new API. After that, the master branch _should_ work as expected though maybe not (I have changed some of the API structure)

**Comment by RedDuckss** [comment]
I'm going to close this issue report now based on the fact that `cemui.com` now points to the API correctly, and based on the fact that the source code in the master branch as well as all previous releases are no longer maintained and supported.

You should be able to change line `869` of `app.js` and remove `.trim()` (since `game_boxart_url` is removed, and replaced with `game_screenshot_urls`) and you should get no errors. However that will mean no games will have backgrounds.

CemUI2.0 is currently in development and should be functional soon, and will be much more stable than this version.
