### ISSUE TITLE
Click delay for games under "Your Library"

### ISSUE THREAD

**Issue by andriyasdf** [RedDuckss/CemUI#52]
Delay due to double click detection seems too long. If it's a feature that's used often, perhaps lower the threshold for double clicking or an option to disable the feature. Alternatively, it could just be removed altogether and another quick launch system could be put in its place.

**Comment by RedDuckss** [comment]
I added the quick launch as a double-click because that was specifically requested (a double-click quick launch). But I agree it's too long, though I believe I have it as short as possible. Any lower and it feels like it becomes less reliable (IE, the timer runs out before the second click is tracked). I would use the native `dblclick` event but it's damn near useless considering the order of event fire. In order, single-click events are fired before double click events making it useless here.

I'm willing to take suggestions on another quick launch method though as I agree the wait time is too long.

**Comment by andriyasdf** [comment]
I do think double click quick launch is indeed a useful feature, so I think when the time comes to implement options this feature should be considered for toggle.

**Comment by RedDuckss** [comment]
Having it as a toggle sounds like the best way to go. I'll disable it by default as well.

**Comment by RedDuckss** [comment]
Closing this as I have found a work around. Double clicking will no longer quick-launch a game. To quick launch you may now use a controller and press the `Start` button (Flux theme only). This change will be in the next build
