### ISSUE TITLE
[Request] Integrated CDcrypt in CemUi like in Wii U Usb Helper

### ISSUE THREAD

**Issue by ThePiranhaPlant** [RedDuckss/CemUI#70]

**Comment by RedDuckss** [comment]
We cannot do this for legal reasons. Nintento has gone on record and stated that decrypting their games violates their copyright and infringes on their IP (Intellectual Property). Because of this, we can _not_ make CemUI do the decrypting. This is why we leave it up to the user, so that CemUI remains perfectly legal.

**Comment by ThePiranhaPlant** [comment]
@RedDuckss Ok
