### ISSUE TITLE
Use the Fluent Theme everywhere

### ISSUE THREAD

**Issue by ThePiranhaPlant** [RedDuckss/CemUI#72]
Because it's more modern and more beautiful.

**Comment by RedDuckss** [comment]
This was the case before but due to popular vote by the people we had test CemUI, we decided to make Flux the default. You can still use the Fluent theme and if you select it, it will remain your default until you change themes.

**Comment by ThePiranhaPlant** [comment]
@RedDuckss Too bad :(  Will you still be able to make sure that when using the Fluent theme the loading screen, settings and downloading of games is in Fluent and not in Flux ?

**Comment by RedDuckss** [comment]
Those are part of the wrapper, which takes influence from Flux (again by popular vote of the testers and development team). Those cannot be changed without moving them out of the wrapper, and that is not an option at the moment.

However since CemUI is open source you can easily change this if you don't like it. You can simply fork the repo and change the styles to match Fluent rather than Flux.
