### ISSUE TITLE
Opening games just opens a new instance of CemUI

### ISSUE THREAD

**Issue by ChildishGiant** [RedDuckss/CemUI#89]
[Video](https://youtu.be/coo3Bu34hYg). It gets pretty laggy pretty quickly. I've only tested this on SMM. Desktop shortcuts do the same thing.

**Comment by RedDuckss** [comment]
It seems like you selected CemUI instead of Cemu during setup. Check your settings and see which executable you selected. Also please copy and paste your confit from %AppData%/CemUI/cache/json

**Comment by ChildishGiant** [comment]
Ah you are right. Sorry for the hassle. Is there any way to change/remove the default path?

**Comment by RedDuckss** [comment]
Currently not from within CemUI due to several oversights by myself. However you can edit the file found in `%AppData%/CemUI/app_data/cache/json/settings.json` and find the cemu path named `Default`:
```
"cemu_paths": [
	{
		"name": "Default",
		"cemu_path": "C:/path/to/incorrect/cemu/Cemu.exe",
		"cemu_folder_path": "C:/path/to/incorrect/cemu"
	}
]
```
Then change both `cemu_path` and `cemu_folder_path` to match the correct paths.

The ability to edit this from within CemUI will be in the next release though I don't have a release date for that

**Comment by RedDuckss** [comment]
Going to close this report now seeing as the initial issue has been answered
